/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _TESTSAMPLE_MOCK_HEAD1_H
#define _TESTSAMPLE_MOCK_HEAD1_H

#include <setjmp.h>
#include "cmock.h"
#include "funky.h"
#include "unity.h"


void test_TheFirstThingToTest(void);
void test_TheSecondThingToTest(void);
#endif
