/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _TESTSAMPLE_HEAD1_H
#define _TESTSAMPLE_HEAD1_H

#include <setjmp.h>
#include "funky.h"
#include "stanky.h"
#include "unity.h"


void test_TheFirstThingToTest(void);
void test_TheSecondThingToTest(void);
void test_TheThirdThingToTest(void);
void test_TheFourthThingToTest(void);
#endif
